- name: Install and configure MariaDB Galera cluster
  hosts: mariadb
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/mariadb.yml

  tasks:

    # Install MariaDB Galera server
    - name: Install MariaDB Galera server
      dnf:
        name: mariadb-server-galera
        state: present

    # Open firewall ports
    - name: Open MariaDB and Galera ports in firewall
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 3306/tcp
        - 4567/tcp
        - 4568/tcp
        - 4444/tcp

    # Reload firewall
    - name: Reload firewall
      service:
        name: firewalld
        state: reloaded

    # Copy bootstrap Galera config for Maria1
    - name: Copy bootstrap Galera config
      template:
        src: ../templates/galera.cnf.j2
        dest: /etc/my.cnf.d/galera.cnf
        owner: root
        group: root
        mode: '0644'
      vars:
        bootstrap: true
      when: inventory_hostname == 'maria1'

    # Bootstrap cluster on Maria1
    - name: Bootstrap MariaDB cluster
      command: galera_new_cluster
      when: inventory_hostname == 'maria1'

    # Enable and start MariaDB on Maria1
    - name: Enable and start MariaDB
      systemd:
        name: mariadb
        enabled: yes
      when: inventory_hostname == 'maria1'

    # Secure MariaDB installation
    - name: Secure MariaDB installation
      expect:
        command: mysql_secure_installation
        responses:
          "Enter current password for root.*": ""
          "Switch to unix_socket authentication.*": "n"
          "Change the root password.*": "n"
          "Remove anonymous users.*": "y"
          "Disallow root login remotely.*": "y"
          "Remove test database and access to it.*": "y"
          "Reload privilege tables now.*": "y"
      when: inventory_hostname == 'maria1'

    # Set Maria1 root password
    - name: Set Maria1 root password
      shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password }}';
        FLUSH PRIVILEGES;
        EOF
      when: inventory_hostname == 'maria1'

    # Replace Maria1 config with full cluster config
    - name: Replace Maria1 Galera config with full cluster config
      template:
        src: ../templates/galera.cnf.j2
        dest: /etc/my.cnf.d/galera.cnf
        owner: root
        group: root
        mode: '0644'
      vars:
        bootstrap: false
      when: inventory_hostname == 'maria1'

    # Copy Galera config for replicas
    - name: Copy Galera config for Maria2 and Maria3
      template:
        src: ../templates/galera.cnf.j2
        dest: /etc/my.cnf.d/galera.cnf
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname != 'maria1'

    # Enable and start MariaDB on replicas
    - name: Enable and start MariaDB replicas
      systemd:
        name: mariadb
        enabled: yes
        state: started
      when: inventory_hostname != 'maria1'
